source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

workspace 'MKHAPIClient'
project 'MKHAPIClient'

use_frameworks!

target 'MKHAPIClient' do

	pod 'MKHSyncSession', :git => 'https://github.com/maximkhatskevich/MKHSyncSession.git'

end