source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

workspace 'MKHCustomAPI'
project 'MKHCustomAPI'

use_frameworks!

target 'MKHCustomAPI' do

	pod 'MKHSyncSession', :git => 'https://github.com/maximkhatskevich/MKHSyncSession.git'

end